// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';


var Index = 0;

var InputForm = 0;

var Component1 = 0;

var Component2 = 0;

exports.Index = Index;
exports.InputForm = InputForm;
exports.Component1 = Component1;
exports.Component2 = Component2;
/* No side effect */
