// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var InputForm$ReactTemplate = require("./InputForm.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, InputForm$ReactTemplate.make(/* array */[])), "main");

/*  Not a pure module */
